include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_empty_else
    - avoid_print
    - avoid_relative_import
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_await_in_return
    - unnecessary_imports
    - use_key_in_widget_constructors
    - prefer_is_not_empty
    - annotate_overrides
    - await_only_futures
    - camel_case_types
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - prefer_collection_literals
    - prefer_contains
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_function_declarations_over_variables
    - prefer_generic_function_type_aliases
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_iterable_whereType
    - prefer_single_quotes
    - slash_for_doc_comments
    - sort_child_properties_last
    - type_init_formals
    - unawaited_futures
    - unnecessary_const
    - unnecessary_getters_setters
    - unnecessary_new
    - unnecessary_null_in_if_null_operators
    - unnecessary_this
    - unrelated_type_equality_checks
    - use_rethrow_when_possible
