import 'dart:io';
import 'package:intl/intl.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';
import '../../features/history/domain/models/audio_chunk.dart';

class ExportService {
  static Future<void> shareAsTxt(AudioChunk chunk) async {
    final date = DateFormat('yyyy-MM-dd_HHmm').format(chunk.startTime);
    final fileName = 'EchoScript_$date.txt';
    
    final text = 'EchoScript Intelligence Report\n'
        'Date: ${DateFormat('EEEE, MMM dd, yyyy').format(chunk.startTime)}\n'
        'Time: ${DateFormat('HH:mm').format(chunk.startTime)}\n\n'
        'Transcription:\n'
        '${chunk.transcription ?? "No transcription available."}';

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$fileName');
    await file.writeAsString(text);

    await Share.shareXFiles([XFile(file.path)], subject: 'EchoScript Report - $date');
  }

  static Future<void> shareAsPdf(AudioChunk chunk) async {
    final pdf = pw.Document();
    final dateFormatted = DateFormat('EEEE, MMM dd, yyyy').format(chunk.startTime);
    final timeFormatted = DateFormat('HH:mm').format(chunk.startTime);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Padding(
            padding: const pw.EdgeInsets.all(32),
            child: pw.Column(
              cross pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'EchoScript Intelligence Report',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
                ),
                pw.SizedBox(height: 16),
                pw.Divider(),
                pw.SizedBox(height: 16),
                pw.Row(
                  main pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('Date: $dateFormatted', style: pw.TextStyle(fontSize: 12)),
                    pw.Text('Time: $timeFormatted', style: pw.TextStyle(fontSize: 12)),
                  ],
                ),
                pw.SizedBox(height: 32),
                pw.Text(
                  'TRANSCRIPTION',
                  style: pw.TextStyle(fontSize: 10, fontWeight: pw.FontWeight.bold, color: PdfColors.grey700),
                ),
                pw.SizedBox(height: 12),
                pw.Text(
                  chunk.transcription ?? 'No transcription available.',
                  style: const pw.TextStyle(fontSize: 14, lineHeight: 1.5),
                ),
                pw.Spacer(),
                pw.Divider(),
                pw.SizedBox(height: 8),
                pw.Align(
                  alignment pw.Alignment.centerRight,
                  child: pw.Text(
                    'Generated by EchoScript v1.1.0',
                    style: pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
                  ),
                ),
              ],
            ),
          );
        },
      ),
    );

    final date = DateFormat('yyyy-MM-dd_HHmm').format(chunk.startTime);
    final fileName = 'EchoScript_$date.pdf';
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$fileName');
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles([XFile(file.path)], subject: 'EchoScript Report - $date');
  }
}
